gemini.api.key=YOUR_GEMINI_API_KEY
# gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
# gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent
# gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-3.5-flash:generateContent
spring.application.name=student-support-chatbot

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/student_chatbot
spring.datasource.username=root
spring.datasource.password=MySQL@123

# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB